--- 
title: "R for Paleolimnology"
author: "Brent Thorne and Dewey Dunnington"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  "bookdown::gitbook":
    df_print: tibble
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: paleolimbot/r4paleolim
description: "A set of R tutorials for paleolimnology."
---

# Introduction {-}

This is the website for the “R for Paleolimnology” workshop given at the [Quebec-Ontario Paleolimnology Symposium (PALS) 2018](http://www.pals2017.com/). Here you will find an expanded version of the given workshop where you will learn how to conduct data science in R with an emphasis on Paleolimnology. You will learn and be able to work on a wide variety of skill sets in R including: how to get your data into R, how to structure your data, how to transform your data, and most importantly, how to visualize your paleolimnological data! By the end of this book we hope that you can take your passion for Paleolimnology and make data analysis enjoyable! No really, it can be enjoyable once you develop these skillsets!

## Prerequisites

R, RStudio, tidyverse

### Installing R and RStudio

Please download both R and RStudio, links below will direct you to the download page, just selesct the appropriate download for your operating system and follow the instructions given!

- [R](https://cran.r-project.org/)
- [RStudio](https://www.rstudio.com/products/rstudio/download/#download)


## Other places to learn R/RStudio/tidyverse

- The book "R for Data Science" [@r4ds] (free online version at http://r4ds.had.co.nz/index.html)
- The [Introduction to the tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse) Data Camp course by David Robinson.
- [tidyverse, visualization, and manipulation basics](https://www.rstudio.com/resources/webinars/tidyverse-visualization-and-manipulation-basics/) tutorial from Garrett Grolemund

## Colophon

This course material was written using the [bookdown](https://bookdown.org/) package inside [RStudio](https://www.rstudio.com/). Pages were built using [Travis CI](http://travis-ci.org), [pandoc](http://pandoc.org/) and [gitbook](https://www.gitbook.com/). The source is [available on github](http://github.com/paleolimbot/r4paleolim).

These tutorials were built with:

```{r}
devtools::session_info(pkgs = c("tidyverse"))
```
